#开头：
Lumi，一个真正“在场”的AI学习搭子！
一个占据孩子每年500小时的桌面入口！
小字：能看见、能听见，并持续理解孩子学习过程的桌面智能终端。

#Problem：
每天都在发生，但没人解决的问题
不会教---讲不明白，一讲就乱
不会陪---缺乏耐心，越陪越崩
不会管---“拖延、粗心、走神、近视”，习惯失控
作业辅导已经成为亲子矛盾爆发的高危时刻。

#商业画布：重新定义“学习”这件事的坐标系

（4象限图）
价值：增负（更高时间投入）=> 减负（更低完成成本）
形式：工具（结果优先）=> 陪伴（过程优先）

增负+工具：各类学习机/自学类产品（洋葱数学/天天练等）
增负+陪伴：各类线上线下培训机构
减负+工具：拍搜类产品/豆包夸克
减负+陪伴：Lumi

减负市场未来三年一定会“爆发”！

#Solution / Lumi是什么？
Lumi不是一个工具，而是一个持续在场的AI终端
看见：持续感知孩子在做什么
理解：理解孩子的学习过程、状态和能力
介入：只在需要的时候出现，提供引导和帮助（非必要，不打扰）
记忆：持续记忆沉淀与整理以形成深度认知
规划：为家长和孩子持续提供策略规划

#Why Hardware
因为90%的学习行为发生在桌面，而不是屏幕！
没有桌面数据，就没有理解力。

#Demo
待上传视频 

#Why Now？
AI第一次可以“理解并实时生成过程”

模型在过去3个月发生的关键跃迁：
多模态理解能力成熟（能听能看）
reasoning能力大幅提升（能理解过程）
**实时结构化生成能力的突破**（能实现realtime dsl output）

从chat-tutor(个性化) => video-tutor（可视化） => dsl-tutor(动态化-可交互、可扩展、可动态注入)
我们本质上是在做一个实时结构化生成系统（Agents + DSL + Memory），这个能力在过去3个月才刚刚成立。

#Moat：桌面数据，会持续转化为优势
我们掌握的是最稀缺、不可替代的“学习过程数据”
两个结果：
用户侧：极强黏性
    越来越懂孩子=>替代成本极高
模型侧：持续进化
    在学习场景中的识别与理解能力持续变强。

展示飞轮：更多用户->更多数据->更懂用户/更强模型->更好体验->更多用户

#Traction
待上传视频

#Business Model：我们做的是入口生意，而不是卖硬件
硬件（获取用户）：
定价：998元
目标：快速铺量，而不是利润

订阅Plus会员（赠送3个月）
年费：约200元/年
提供持续能力与服务

长期价值（数据价值变现）
增值服务（仅限家长端，绝不影响孩子体验）

商业容量：装机量*活跃时长


#GTM ：制造新物种的Go viral时刻
第一阶段：制造Aha Moment（冷启动）
拍摄真实孩子使用场景
强情绪瞬间（“第一次被替代”）
社媒种草 + 小规模传播
目标：3个月验证产品是否自带传播性（pmf信号）

第二阶段：放大势能（起量）
达人带货 + 电商平台推广
标准化内容 + 转化模型
目标：3-12月快速出圈，占领品类心智

第三阶段：口碑飞轮（阵地战）
粉丝私域+自传播（晒娃）
社群与复购驱动
目标：降低获客成本，形成自增长

我们不是先铺渠道，而是先制造“必须传播的Aha Moment”

#Why us
张昊波：产品
12年专注个性化学习的产品化
百度：信息理解与算法
作业盒子：学习数据与个性化
高途：跑通商业闭环

陈磊：技术
专注Agentic系统大规模落地
百度：手百信息流负责人
京东：主站APP技术负责人，落地过亿级用户的服务
独立创业：银发赛道独立创业，服务超过500万用户，百万级年营收

我们6年前就一起创业过，这是第二次合作；

#Vision
这是一个全新的入口级机会，我们在帮助父母和孩子以更轻松的姿态面对学习；

#附录：
市场规模
BOM成本
时间计划
数据
竞品效果视频